### ISSUE TITLE
Необходимо сверстать страницу создания конкурса.

### ISSUE THREAD

**Issue by semen1032** [Seterator/seterator.ru#28]
В данный момент уже возможно создавать конкурс с минимальными параметрами через прямую ссылку. Сейчас страница выглядит так:
![image](https://user-images.githubusercontent.com/51064226/69357207-c3088f80-0c95-11ea-89c7-17190a2ae60c.png)

Требуется изменить дизайн этой страницы в соответствие с макетом, который выслал дизайнер. 
Поля, которые еще не реализованы следует заменить заглушками.

**Comment by BearPro** [comment]
Не заменяй ничего заглушками. Что там ещё нужно? Если опишешь модель данных, которая тебе нужна для этой страницы - я напишу готовый контроллер.

Я лично могу только выпадающий список жюри придумать из того, чего не хватает. Для этого могу замутить отдельный контроллер.

**Comment by semen1032** [comment]
> Не заменяй ничего заглушками. Что там ещё нужно? Если опишешь модель данных, которая тебе нужна для этой страницы - я напишу готовый контроллер.
> 
> Я лично могу только выпадающий список жюри придумать из того, чего не хватает. Для этого могу замутить отдельный контроллер.

Мне требуется контроллер, принимающий такие поля как:
1. Социальные сети организатора (не требуется в минимальном функционале, оставляем на будущее);
2. Номер телефона организатора (не зависит от данных профиля, организатор заполняет вручную);
3. Электронная почта организатора (также не зависит от данных профиля);
4. ? Категория конкурса (пока что не совсем понятно, так как в макете не указано, что поле можно редактировать - скорее всего будет редактироваться в будущем);
4. Название конкурса;
5. Короткое описание конкурса;
6. Изображение на фон конкурса;
7. Полное описание конкурса;
8. Условия конкурса (пока что представлены только самые базовые):
8.1 Возраст участников (от до);
8.2. Страны участников;
8.3. Ссылка на подробные условия;
8.4. Документ с условиями;
8.5. Документ "Политика конфиденциальности";
8.6. Документ "Соглашение";
8.7. Документ "Доп. документ";
9. Призовые места:
9.1 Место (от до);
9.2. Описание приза;
10. Жюри (плохо представляю себе систему выбора жюри):
10.1. Пока что ограничимся списком ссылок на профили жюри тогда.

Также требуется контроллер, хранящий черновики полу-созданных конкурсов.

**Comment by BearPro** [comment]
@semen1032 В целом всё ок.
>Категория конкурса

Guid категории конкурса, (нужно будет добавить контроллер возвращающий возможные категории).

>Изображение на фон конкурса

Пикчи всё ещё откладываем, я до сих пор не знаю как их делать. Можно конечно использовать какой-нибудь Base64 Encode, но нужно ещё подумать. К тому же, хранить это пока-что негде, кроме как в json'е, а это неправильно.

>Условия конкурса

У нас отдельная таблица с условиями. Там формат: название ограничения ("Возраст", Рост", "Рейтинг") и числовой диапозон "От" и "До". 

>Призовые места

Пока что - тупо JSON. Потом придумаем что-нибудь поумнее. По хорошему, надо и для этого отдельную таблицу делать.

> Жюри

Не список ссылок на профили, а список guid профилей жюри. Опять же, намутим контроллер возвращающий список жюри, чтобы было из чего выбирать юзеру. Ты там выпадающий список намутишь какой-нибудь. Не вижу проблемы.
***
Попробуй описать пример возможного json, который ты мог бы отправлять, или дождись пока я вернусь домой и замучу класс для модели запроса.

Контроллеры тоже постараюсь сделать сегодня.

**Comment by semen1032** [comment]
@BearPro, сейчас стоит оставить только минимальные данные:
{
"organizer_phone": "89000000000",
"organizer_mail": "qq@seterator.ru",
"category": "everyday",
"title": "Конкурс поэтического мастерства",
"short_description": "Основные идеи",
"description": "Подробное описание конкурса",
"constraints": [...],
"prizes": [...],
"jury": [...]
}

Условия конкурса и призы мы уже обсуждали, точно не помню их вид. Жюри придумаешь сам как описывать. 

Социальные сети организатора, изображение на фон, загрузка документов пока не предполагается.

**Comment by semen1032** [comment]
Проблема данного issue решена, но существует еще много работы над доработкой страницы создания конкурса. Для этого будет открыт новый issue с более глобальной проблемой.
