### ISSUE TITLE
Сделать рабочий счётчик на странице Participant/Become

### ISSUE THREAD

**Issue by BearPro** [Seterator/seterator.ru#30]
Сейчас счётчик не работает и показывает константное значение.
![image](https://user-images.githubusercontent.com/13729660/69418674-3ceb5800-0d2c-11ea-8396-b9020e902778.png)

**Comment by semen1032** [comment]
@BearPro, жду контроллер, без него проблему не решить.

**Comment by BearPro** [comment]
> 
 
> @BearPro, жду контроллер, без него проблему не решить.

Какой контроллер тебе нужен?

**Comment by semen1032** [comment]
> > 
> 
> > @BearPro, жду контроллер, без него проблему не решить.
> 
> Какой контроллер тебе нужен?

Вопрос решен. Использую api Participant/Competition/guid
