### ISSUE TITLE
Проект на релизной конфигурации не компилируется

### ISSUE THREAD

**Issue by BearPro** [Seterator/seterator.ru#37]
**Что случилось?**
При попытке выполнить сборку на релизной конфигурации компилятор выпадает с ошибкой.

**Как воспроизвести?**
1. Выполнить команду `dotnet build -c Release`
2. Наблюдать ошибки сборки

**Описание**
Вывод компилятора:

    dotnet build -c Release
    Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
    Copyright (C) Microsoft Corporation. All rights reserved.
    
      Restore completed in 240.96 ms for C:\Users\BearPro\source\Workspaces\Rauthor\Rauthor\Rauthor.csproj.
      Restore completed in 245.81 ms for C:\Users\BearPro\source\Workspaces\Rauthor\Rauthor.UnitTests\Rauthor.UnitTests.csproj.
    C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(187,5): warning NETSDK1071: A PackageReference to     'Microsoft.AspNetCore.App' specified a Version of 2.2.7. Specifying the version of this package is not recommended. For more information, see https://aka.ms/sdkimplicitrefs    [C:\Users\BearPro\source\Workspaces\Rauthor\Rauthor\Rauthor.csproj]
    C:\Users\BearPro\source\Workspaces\Rauthor\Rauthor\wwwroot\js\Competition\all.ts(2,52): error TS2705: Build:An async function or method in ES5/ES3 requires the 'Promise'   constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your --lib option.    [C:\Users\BearPro\source\Workspaces\Rauthor\Rauthor\Rauthor.csproj]
    
    Build FAILED.

Видно, что это какая-то ошибка typescript, связанная с отстутсвием нужной либы для типа `Promise<T>`.
Поверхностное гугление показало, что это распространённая проблема, но решение найти не помогло.

Характерно, что ошибка не возникает при сборке с отладочной конфигурацией (по умолчанию, или `dotnet build -c Debug`)

**Comment by semen1032** [comment]
Предлагаю пока что обойтись нативным JSом. Я еще не лез в ts и в ближайшее время не собирался, так что решать проблему пока не буду.

**Comment by BearPro** [comment]
> Предлагаю пока что обойтись нативным JSом. Я еще не лез в ts и в ближайшее время не собирался, так что решать проблему пока не буду.

Ну тогда выпили его просто. Мне для тестирования крайне желательно иметь возможность собрать всё в релизе.

**Comment by semen1032** [comment]
> > Предлагаю пока что обойтись нативным JSом. Я еще не лез в ts и в ближайшее время не собирался, так что решать проблему пока не буду.
> 
> Ну тогда выпили его просто. Мне для тестирования крайне желательно иметь возможность собрать всё в релизе.

Хорошо, посмотрю, что можно сделать.

**Comment by semen1032** [comment]
Проверил релизную сборку проекта. Ошибка возникает в файле all.ts. Также я заметил, что файл create.ts компилируется в js и перезаписывает файл create.js.

Файлы, написанные на typescript являлись временными, пока что будем писать только на js. Поэтому я удалю все TypeScript файлы, это ни на что не повлияет и исправит ошибку компиляции.

**Comment by semen1032** [comment]
После удаления временных файлов TypeScript релизная версия проекта компилируется успешно.
