### ISSUE TITLE
Неправильно отображаются svg картинки в браузере Edge.

### ISSUE THREAD

**Issue by semen1032** [Seterator/seterator.ru#42]
**Что случилось?**
Поступает много жалоб, что в шапке неправильно отображается svg иконка авторизации, также на странице регистрации/авторизации съехало и раздулось окно с формой из-за слишком больших иконок соц сетей.

**Как воспроизвести?**
1. Открыть браузер Edge;
2. Перейти на любую страницу;
3. Увидеть большую иконку в шапке;
4. Перейти на страницу авторизации/регистрации;
5. Увидеть раздувшуюся форму.

**Описание**
Вероятно, проблема возникла после переписывания блока социальных сетей под БЭМ методологию. Новая реализация была протестирована только в Chrome и Firefox.

**Как исправить?**
Скорее всего, нужно задать svg картинкам width: 100%.

**Comment by BearPro** [comment]
Есть годный хак для бразуеров IE и Edge, можно посмотреть тут:

 - https://github.com/thepracticaldev/dev.to/pull/3553
 - https://github.com/thepracticaldev/dev.to/commit/84df7e51f4602af83f4c09d66112c5f4e7041e67

Там в обсуждении упоминается [годная страница с хаками](https://bl.ocks.org/feo52/raw/b6198873e0bbaeda098e4ca6f62ca887/).

**Comment by semen1032** [comment]
> Есть годный хак для бразуеров IE и Edge, можно посмотреть тут:
> 
> * [thepracticaldev/dev.to#3553](https://github.com/thepracticaldev/dev.to/pull/3553)
> * [thepracticaldev/dev.to@84df7e5](https://github.com/thepracticaldev/dev.to/commit/84df7e51f4602af83f4c09d66112c5f4e7041e67)
> 
> Там в обсуждении упоминается [годная страница с хаками](https://bl.ocks.org/feo52/raw/b6198873e0bbaeda098e4ca6f62ca887/).

В данном случае это не нужно, так как было необходимо просто немного переписать css селекторы для svg иконок.
