### ISSUE TITLE
Не отображаются данные о конкурсе без авторизации.

### ISSUE THREAD

**Issue by semen1032** [Seterator/seterator.ru#52]
**Что случилось?**
На странице конкурса неавторизованным пользователям не выводятся данные о конкурсе.

**Как воспроизвести?**
1. Перейти на seterator.ru
2. Без авторизации кликнуть на любой конкурс

**Описание**
Скрипт, выводящий информацию о конкурсе работает неправильно. Без авторизации в консоли отображается ошибка:
![image](https://user-images.githubusercontent.com/51064226/69791018-a956d300-11d4-11ea-9744-1d881c136b8d.png)
Возможно, неправильно работает контроллер, ограничивая незарегистрированного пользователя на просмотр данных конкурса.

**Comment by BearPro** [comment]
Да, действительно, сервер кидает перенаправление на страницу входа.
На методах, возвращающих список соревнований и детали конкретного соревнования, стоят атрибуты `[Authorize(Roles = "User")]`. Сейчас пофикшу.

**Comment by BearPro** [comment]
В #55 ошибка исправлена.
