### ISSUE TITLE
Нужен контроллер, возвращающий роль пользователя.

### ISSUE THREAD

**Issue by semen1032** [Seterator/seterator.ru#68]
**Проблема, с которой я столкнулся**
Для того, чтобы внедрить управление ролями на страницах, например, на странице профиля выводить необходимую информацию в зависимости от роли.

**Описание**
Мне необходим контроллер, который возвращает роль пользователя, который авторизован в системе. Также, если пользователь не авторизован, то контроллер также должен это возвращать.

**Comment by BearPro** [comment]
В каком виде хочешь получать роли? То что сейчас возвращает ProfileController (который api) для конкретного пользователя не подходит?

**Comment by semen1032** [comment]
А в каком виде возвращает роли ProfileController? Ты это нигде не описывал.

**Comment by semen1032** [comment]
Более полно проблема описана в #116
