### ISSUE TITLE
Требуется обновить/задокументировать шаблон json'а с условиями конкурса

### ISSUE THREAD

**Issue by semen1032** [Seterator/seterator.ru#80]
# Условия конкурса

Условия могут быть нескольких типов. В данный момент существуют следующие:
1. Словарь:
   * Возраст: 18 
   * Страна: Россия
2. Строка:
   * Условие пишется в одну строку
3. Файл:
   * *Картинка файла* Название файла
   * Причем, при назжатии на название загружается документ
 
На основании всего этого предлагаю ввести такой json шаблон для условия конкурса:

```
    {
        "type": "dict",
        "name": "Возраст",
        "value": [
            "18",
            "19"
        ]
    }
```

### Тип словарь

```
    {
        "type": "dict",
        "name": "Возраст",
        "value": [
            "18",
            "19"
        ]
    }
```

### Тип строка

```
    {
        "type": "line",
        "name": "Условие конкурса, написанное в одну строку",
        "value": [
        ]
    }
```

### Тип файл

```
    {
        "type": "file",
        "name": "Соглашение",
        "value": [
            "/img/Competition/document.svg",
            "/files/document.pdf"
        ]
    }
```
## Как это выглядит у дизайнера:

![image](https://user-images.githubusercontent.com/51064226/74099782-2fc65400-4b38-11ea-8b07-0bb99c1752be.png)

**Comment by semen1032** [comment]
@BearPro @saner99 Предлагаю обсудить необходимые типы условий и поля шаблона.
На мой взгляд, данный шаблон является компактным, а также достаточно расширяемым при необходимости ввода новых типов.

**Comment by semen1032** [comment]
Вообще, мне кажется, пора начать документировать наши api. Потому что все, что обсуждается на словах и в соц сетях имеет способность забываться/теряться. 

Помню, @BearPro, собирался настроиться swagger, но, мне кажется, что для начала можно использовать wiki страницу нашего проекта для этого.

**Comment by BearPro** [comment]
>пора начать документировать наши api.

api полностью документируют типы, определённые в серверной части.

Нужно определиться с тем, в каком формате мы будем хранить, отправлять и передавать бинарные файлы (пока это пикчи и pdf-ки).

Введение ограничений в таком формате требует большого обсуждения, придётся добавить в схему БД много новых сущностей для соответствия [формату].

**Comment by BearPro** [comment]
Сеёма, произвольных условий у конкурса до релиза не будет. Только "от-до" и "наборы" (наборы - типа страны в которой зарегистрирован пользователь
