### ISSUE TITLE
Требуется обновить/задокументировать шаблон json'а с призами конкурса

### ISSUE THREAD

**Issue by semen1032** [Seterator/seterator.ru#81]
# Призы конкурса

В данном разделе у нас есть такие поля как место, значение приза.
Насколько я понимаю, при создании конкурса возможно указывать диапазоны мест, а также перечислять их через запятую. Также в ТЗ указано, что места разных призов могут пересекаться, но это по сути никак не сказывается на json.

**В связи с этим предлагаю ввести такой стандарт на json с призами конкурса:**

```
    {
        "value": "Футболка",
        "range": [
            {
                "start": 1,
                "end": 3
            },
            {
                "start": 10,
                "end": 13
            }
        ],
        "optional": [
            6,
            9
        ]
    }
```

В поле *range* записываются диапазоны мест, которым удовлетворяет данный приз (начальное и конечное значения включаются). Также здесь предусмотрено несколько диапазонов мест на всякий случай.
Вообще, это можно сократить и вместо объектов с полями (start и end) использовать массивы из двух элементов, чтобы сократить место, но, как мне кажется, это будет менее читаемо и места тратится не критично больше.

Поле *optional* указывает на отдельные места, указывающиеся через запятую, которые в диапазон не входят. 

Также прилагаю скрин от дизайнера для визуализации:
![image](https://user-images.githubusercontent.com/51064226/74101884-6c517a00-4b4f-11ea-9037-1c19be49d45f.png)

@bearpro @saner99 как вам такой json? Если есть что добавить/исправить, прошу выдвинуть на обсуждение.

**Comment by semen1032** [comment]
Сейчас думал над отображением этих данных и решил, что изначальный вариант достаточно сложен, поэтому предлагаю немного измененный вариант:

```
{
        "value": "Футболка",
        "range": [
            {
                "start": 1,
                "end": 3
            },
            {
                "start": 10,
                "end": 13
            },
            {
                "start": 6,
                "end": null
            },
            {
                "start": 9,
                "end": null
            }
    }
```

Или как более компактный вариант, но менее читаемый можно записывать так:

```
{
        "value": "Футболка",
        "range": [
            [1, 3],
            [10, 13],
            [6],
            [9]
    }
```

**Comment by semen1032** [comment]
Написал код, основываясь на самый последний (кротчайший) вариант. Все отлично работает, так что склоняюсь к нему.

**Comment by BearPro** [comment]
Согласен с последним компактным вариантом. Так и реализуем.
