### ISSUE TITLE
Требуется обновить/задокументировать шаблон json'а с жюри конкурса

### ISSUE THREAD

**Issue by semen1032** [Seterator/seterator.ru#82]
# Жюри конкурса

Так как мы нигде не утверждали формат json'а для жюри конкурса, предлагаю свой вариант видения этой картины. 

```
    {
        name: "Александр Новожилов",
        description: "Пока у нас нет жюри, оценивать всех будет он.",
        avatar: "/img/saner99.png",
        pagelink: "seterator.ru/saner99"
    }
```

Пока что для страницы с отображением конкурса этого достаточно, но если потребуется что-то еще, всегда можно добавить полей.

Выше описывался формат для элемента жюри из списка всех жюри.

_Как видит это дизайнер:_

![image](https://user-images.githubusercontent.com/51064226/74108055-303a0b80-4b87-11ea-9cac-8314ede29015.png)

@bearpro @saner99 если есть что добавить/изменить - пишите.

**Comment by BearPro** [comment]
Профили хранятся как JSON, сервер его никак не обрабатывает, а просто по запросу сохраняет и по запросу же отдаёт (или будет отдавать)
