### ISSUE TITLE
Требуется обновить/задокументировать шаблон json'а с участниками конкурса 

### ISSUE THREAD

**Issue by semen1032** [Seterator/seterator.ru#83]
# Участник конкурса

Так как мы нигде не утверждали формат json'а для участника конкурса, предлагаю свой вариант видения этой картины. 

```
    {
        "nickname": "Псевдоним участника",
        "poems": [
            {
                "title": "Название произведения",
                "poem": "Текст произведения",
                "guid": "guid заявки"
            }
        ],
        "guid": "guid участника"
    }
```

Пока что для страницы с отображением конкурса этого достаточно, но если потребуется что-то еще, всегда можно добавить полей.

Как видит это дизайнер:
![image](https://user-images.githubusercontent.com/51064226/74110703-d1cd5700-4b9f-11ea-9231-e3ddd4eb17fb.png)

@bearpro @saner99 если есть что добавить/изменить - пишите.

**Comment by BearPro** [comment]
Это формат данных для GET-запроса? POST-ить guid-ы не нужны, это может создать лишние проблемы.

**Comment by semen1032** [comment]
> Это формат данных для GET-запроса? POST-ить guid-ы не нужны, это может создать лишние проблемы.

Да, это был описан GET-запрос. В POST'е конечно же guid'ов не будет.

**Comment by BearPro** [comment]
Guid автора точно не хочешь?
