### ISSUE TITLE
Организовать ведение логов

### ISSUE THREAD

**Issue by BearPro** [Seterator/seterator.ru#92]
**Проблема, с которой я столкнулся**
Сайт периодически падает, ответить на вопрос "почему?" сейчас невозможно, так как логи не ведутся вообще.

**Описание решения**
Нужно организовать нормальное логгирование.

**Comment by shayakhmetov94** [comment]
Предлагаю для логирования использовать NLog: https://www.loggly.com/blog/benchmarking-5-popular-net-logging-libraries/

**Comment by BearPro** [comment]
Тема годная! Выглядит очень круто.

**Comment by BearPro** [comment]
Возможно, стоит попробовать интегрировать NLog с встроенным сервисом логгирования (сейчас она занимается выводом лога на консоль, .AddLogging() в Startup.cs), и увеличить количество полезных данных в логах - статусы ответов, выбранные маршруты и методы контроллеров, возникающие исключения.
