### ISSUE TITLE
Библиотеки хранятся в репозитории.

### ISSUE THREAD

**Issue by semen1032** [Seterator/seterator.ru#93]
**Описание**

Все библиотеки, связанные с фронтендом, хранятся в репозитории, увеличивая тем самым его размер. 
Так как мы уже настроили работу с зависимости через npm, необходимо перенести подключение библиотек в _package.json_, чтобы они хранились в папке _node_modules_ и не засоряли репозиторий. 

В данный момент в репозитории в директории _wwwroot/lib/_ лежат:

- bootstrap
- jquey
- vue

**Предполагаемое решение**

Удалить все библиотеки из директории _wwwroot/lib/_.
Прописать в зависимости файла _package.json_ необходимые библиотеки.
В файлах подключения библиотек изменить путь.

**Comment by BearPro** [comment]
Эта же проблема упоминалась в #78

**Comment by semen1032** [comment]
Действительно, дублирование #78.
