### ISSUE TITLE
В некоторых окружениях проект запускается только с IIS

### ISSUE THREAD

**Issue by BearPro** [Seterator/seterator.ru#94]
**Что случилось?**
Во время настройки рабочего окружения у одного из разработчиков возникла потребность в установке пакета `Microsoft.AspNetCore.Server.IISIntegration`. Без него возникала ошибка `Application is running inside IIS process but is not configured to use IIS server`, но при этом проект корректно компилировался и запускался.

**Comment by shayakhmetov94** [comment]
Отактил полностью все изменения и заново запустил проект. Ошибка `Microsoft.AspNetCore.Server.IISIntegration` более не возникала. Причины ошибки не ясны. Предлагаю напрасно не тратить время на разбирательство и закрыть запрос.

**Comment by BearPro** [comment]
Согласен, сейчас разбираться с этим не актуально.
